export const types = {
    CHANGE_TITLE: "[TITLE]/CHANGE_TITLE",
    CHANGE_DATA:"CHANGE_DATA",
    ADD_USER: "ADD_USER",
    CLEAR_DATA: 'CLEAR_DATA',
    CREATE_USER: "CREATE_USER",
    ADD_NUMBER:"ADD_NUMBER"
}